sudo: required
services:
  - docker

before_install:
  - docker build -t ylmsolutionsltd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ylmsolutionsltd/docker-react npm run test -- --coverage