sudo: required
services: 
  - docker

before_install:
  - docker build -t ylmsolutionsltd/docker-react -f Dockerfile.dev .

script:
  - docker run  ylmsolutionsltd/docker-react  -e CI=true npm run test 